<a href="https://colab.research.google.com/github/Pranali-Patil-1212/Python_Project_Module/blob/main/NumPy_Pandas_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy
-NumPy is a open source, python package used for scientific and numerical computations

-NumPy is a Python library used for working with arrays

-NumPy stands for Numerical Python
#Features:
1. Efficient array object(n dimensional array)->faster than list
2. Verctorized operations
3. foundation of data science and ML libraries like pandas, scikit learn, tensor flow

In [ ]:
#importing the numpy package
import numpy as np

#creating an array using numpy
arr=np.array([1,2,3,4,5,6])
print(arr)

#version of numpy
print("Version of numpy=", np.__version__)

#creating n dimensional array
#To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray
arr1=np.array((2,4,6,8,10))
print(arr1)

#or
list=(2,4,6,8,10)
arr2=np.array(list)
print(arr2)

# 1-Dimensional array
arr1D=np.array([1,2,3,4])
print("This is 1-dimensional array=", arr1D)

# 2-Dimensional array
arr2D=np.array([[1,2,3],
                [4,5,6]
                ])
print("This is 2-Dimensional array=", arr2D)
# 3-Dimensional array with 2-D
arr3D=np.array([[[1,2,3],
                 [4,5,6]
                 ],
                 [[7,8,9],
                  [6, 4,3]
                  ]])
print("This is 3-Dimensional array=", arr3D)

#Check Number of Dimensions of array
print("Number of dimensions of arr1D is=", arr1D.ndim)
print("Number of dimensions of arr2D is=", arr2D.ndim)
print("Number of dimensions of arr3D is=", arr3D.ndim)

#Slicing Arrays
print("############### Slicing Array ##############")
array1=np.array([1,2,3,4,5,6,7,8,9,10])
print(array1[1:5]) #it will slice from index 1 to 4
print(array1[2:]) #it will slice from index 2 to end of array element
print(array1[:4]) #it will slice from start index element to the 3 element

#Negative indexing
print("######## Negative Slicing #########")
print(array1[-4:-1])
print(array1[1:5:1])

#Slicing 2-Dimensional array
arr2d=np.array([[1,2,3,4,5], [6,7,8,9,10]])
print("slicing of 2dimensional array from second array=",arr2d[1, 1:4])
print("slicing of 2dimensional array from first array=",arr2d[0, 1:4]) #From the second element, slice elements from index 1 to index 4 (not included)
print("slicing of data from both array=", arr2d[0:2, 2]) #From both elements, return index 2
print(arr2d[0:2, 1:4]) #From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:

#Creating an array with defined datatype
array3=np.array([11,12,13,14], dtype='S') #it will create an array with data type string
print(array3)
print("Datatype of array3 is=", array3.dtype)

array4=np.array([11,22,33,44], dtype="i")
print(array4)
print("Datatype of array4 is=", array4.dtype)

print("############## NumPy array Shape ################")
#NumPy array shape
#Shape of an arraay is the number of elements in each dimension
print("Shape of array1D is=", arr1D.shape)
print("Shape of array2D is=", arr2.shape)
print("Shape of array3D is=", arr3D.shape)

#Reshaping arrays
print("############## Reshaping arrays ################")
#Reshaping means changing the shape of an array.
#The shape of an array is the number of elements in each dimension.
#By reshaping we can add or remove dimensions or change number of elements in each dimension
arrayy=np.array([2,3,8,6,4,43,42, 1, 3,7,4, 1])
newarr=arrayy.reshape(4,3)
print(newarr)
newarr1=arrayy.reshape(1,12)
print(newarr1)



[1 2 3 4 5 6]
Version of numpy= 2.0.2
[ 2  4  6  8 10]
[ 2  4  6  8 10]
This is 1-dimensional array= [1 2 3 4]
This is 2-Dimensional array= [[1 2 3]
 [4 5 6]]
This is 3-Dimensional array= [[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [6 4 3]]]
Number of dimensions of arr1D is= 1
Number of dimensions of arr2D is= 2
Number of dimensions of arr3D is= 3
############### Slicing Array ##############
[2 3 4 5]
[ 3  4  5  6  7  8  9 10]
[1 2 3 4]
######## Negative Slicing #########
[7 8 9]
[2 3 4 5]
slicing of 2dimensional array from second array= [7 8 9]
slicing of 2dimensional array from first array= [2 3 4]
slicing of data from both array= [3 8]
[[2 3 4]
 [7 8 9]]
[b'11' b'12' b'13' b'14']
Datatype of array3 is= |S2
[11 22 33 44]
Datatype of array4 is= int32
############## NumPy array Shape ################
Shape of array1D is= (4,)
Shape of array2D is= (5,)
Shape of array3D is= (2, 2, 3)
############## Reshaping arrays ################
[[ 2  3  8]
 [ 6  4 43]
 [42  1  3]
 [ 7  4  1]]
[[ 2  3  8  6  4 

In [ ]:
import numpy as np

#Array Object Attribute
array1=np.array([1,2,3,4,5,6])
print("shape of array=", array1.shape)

# Dimensions of array
print("dimensions of array=", array1.ndim)

#Array Creations functions
print("###### Array Creation Functions ###############")
print(f"arange function= {np.arange(0,10, 2)}")
print(f"Line Spacing function={np.linspace(1, 20, 10)}")
print(f"Log space function={np.logspace(1, 20, 3)}")

# 2-Dimensional array (Matrix calculations)
print("###### Matrix Calculations ###############")
print("===>>> 3 By 3 matrix")
print(np.eye(3)) #create 3by 3 matrix

print("===>>>> 3 By 3 matrix with random values")
print(np.random.rand(3,3)) #create 3by 3 matrix with random values

print("===>> 3 by 3 martrix with zeros")
print(np.zeros((3,3))) #create 3by 3 matrix with zeros

print("===>> 3 by 3 matrix with ones")
print(np.ones((3,3))) #create 3by 3 matrix with ones


#Performing operations on array
# To perform arithmetic operations on two array the size of both arrays should be same
print("###### Performing operations on array ###############")
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,1,9])
print("Addition of two arrays=", arr1+arr2)
print("Subtraction of two arrays=", arr1-arr2)
print("Multiplication of two arrays=", arr1*arr2)
print("Division of two arrays=", arr1/arr2)

#To perform the matrix multiplication no of colums of first matrix is equal to the no of rows of second matrix
matrix1=np.array([[1,2,3], [6,3,5]] )

matrix2=np.array([[1,2,3], [6,3,5], [3,2,2]])
print("Matrix multiplication=", np.dot(matrix1, matrix2))

#dir(np)
array=np.array([10,34,56, 89, 3, 2])
print(f"Maximum no={np.max(array)}")
print(f"Minimum no={np.min(array)}")
print(f"Mean of array={np.mean(array)}")
print(f"Median of array={np.median(array)}")
print(f"Standard deviation of array={np.std(array)}")
print(f"Variance of array={np.var(array)}")
print(f"Tan of array={np.tan(array)}")
print(f"Sin of array={np.sin(array)}")
print(f"Cos of array={np.cos(array)}")
print(f"Log of array={np.log(array)}")

shape of array= (6,)
dimensions of array= 1
###### Array Creation Functions ###############
arange function= [0 2 4 6 8]
Line Spacing function=[ 1.          3.11111111  5.22222222  7.33333333  9.44444444 11.55555556
 13.66666667 15.77777778 17.88888889 20.        ]
Log space function=[1.00000000e+01 3.16227766e+10 1.00000000e+20]
###### Matrix Calculations ###############
===>>> 3 By 3 matrix
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
===>>>> 3 By 3 matrix with random values
[[0.76817383 0.14569703 0.40779951]
 [0.34059098 0.10619767 0.99485821]
 [0.16070413 0.94041307 0.48727531]]
===>> 3 by 3 martrix with zeros
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
===>> 3 by 3 matrix with ones
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
###### Performing operations on array ###############
Addition of two arrays= [ 7  9 11  5 14]
Subtraction of two arrays= [-5 -5 -5  3 -4]
Multiplication of two arrays= [ 6 14 24  4 45]
Division of two arrays= [0.16666667 0.28571429 0.375      4.         0.55555556]
Matrix multipl

# Pandas

-Pandas is a popular package of python used to organize, manipulate(analyze the data and perform some operations) and visualize the dataset

-Data sets in Pandas are usually multi-dimensional tables, called DataFrames.

-Pandas is mostly used for organization and manipulations and rarely used for visualization

-Pandas is a Python library used for working with data sets.

-It has functions for analyzing, cleaning, exploring, and manipulating data.

-Pandas has two objects

1)Series => 1-Dimensional labelled array eg. list

-A Pandas Series is like a column in a table.

-It is a one-dimensional array holding data of any type
2)DataFrame => 2-Dimensional representation where data is organized in row and columns manner

In [ ]:
import pandas as pd


lst=[1,2,4,3,5,3]
print("without pandas list is=", lst)
list2 = pd.Series(lst)
print("============================================"*2)
print("using pandas the list is=", list2)

#Customizing the indexes
print("============================================"*2)
print("Customizing indexes")
list3 = pd.Series(lst, index=['a', 'b', 'c', 'd', 'e', 'f'])
print(list3)
print("the element at index a is=", list3['a'])

#Define DataFrame
print("============================================"*2)
print("Define DataFrame")
dct={
    "Name":["Pranali", "Sourabh", "Deepak", "Devyani"],
    "Age":[23, 20, 24, 22],
    "Sex":["Female", "Male", "Male", "Female"]
}
df=pd.DataFrame(dct)
print(df)

#Customizing the index of dataframe
print("================="*2)
df1=pd.DataFrame(dct, index=["x", "y", "z", "p"])
print(df1)

without pandas list is= [1, 2, 4, 3, 5, 3]
using pandas the list is= 0    1
1    2
2    4
3    3
4    5
5    3
dtype: int64
Customizing indexes
a    1
b    2
c    4
d    3
e    5
f    3
dtype: int64
the element at index a is= 1
Define DataFrame
      Name  Age     Sex
0  Pranali   23  Female
1  Sourabh   20    Male
2   Deepak   24    Male
3  Devyani   22  Female
      Name  Age     Sex
x  Pranali   23  Female
y  Sourabh   20    Male
z   Deepak   24    Male
p  Devyani   22  Female


In [ ]:
#Working with Reak data
data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/diabetes.csv")


In [ ]:
#Get top 5 rows
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
#get top 20 rows
data.head(20)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0             6      148             72             35        0  33.6   
1             1       85             66             29        0  26.6   
2             8      183             64              0        0  23.3   
3             1       89             66             23       94  28.1   
4             0      137             40             35      168  43.1   
5             5      116             74              0        0  25.6   
6             3       78             50             32       88  31.0   
7            10      115              0              0        0  35.3   
8             2      197             70             45      543  30.5   
9             8      125             96              0        0   0.0   
10            4      110             92              0        0  37.6   
11           10      168             74              0        0  38.0   
12           10      139             80              0        0  27.1   
13            1      189             60             23      846  30.1   
14            5      166             72             19      175  25.8   
15            7      100              0              0        0  30.0   
16            0      118             84             47      230  45.8   
17            7      107             74              0        0  29.6   
18            1      103             30             38       83  43.3   
19            1      115             70             30       96  34.6   

    DiabetesPedigreeFunction  Age  Outcome  
0                      0.627   50        1  
1                      0.351   31        0  
2                      0.672   32        1  
3                      0.167   21        0  
4                      2.288   33        1  
5                      0.201   30        0  
6                      0.248   26        1  
7                      0.134   29        0  
8                      0.158   53        1  
9                      0.232   54        1  
10                     0.191   30        0  
11                     0.537   34        1  
12                     1.441   57        0  
13                     0.398   59        1  
14                     0.587   51        1  
15                     0.484   32        1  
16                     0.551   31        1  
17                     0.254   31        1  
18                     0.183   33        0  
19                     0.529   32        1

In [ ]:
#Get bottom 5 rows
data.tail()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0

In [ ]:
#get bottom 8 rows
data.tail(8)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
760            2       88             58             26       16  28.4   
761            9      170             74             31        0  44.0   
762            9       89             62              0        0  22.5   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
760                     0.766   22        0  
761                     0.403   43        1  
762                     0.142   33        0  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0

In [ ]:
#Getting the shape of data (no of rows and columns in data)
data.shape

(768, 9)

In [ ]:
#getting names of columns
data.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [ ]:
# Summary of Dataframe
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [ ]:
# Statistical summary of dataframe
data.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [ ]:
# Data Access Methods in Pandas
# 1) loc() => used with labels
# 2) iloc() => used with indexes

print(data.loc[1, "Pregnancies"])
print(data.loc[3, "BloodPressure"])

print(data.iloc[1,1])

1
66
85


In [ ]:
# Assigning the value
data.loc[2, "Glucose"]=100
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      100             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      100             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
#Slicing
data.iloc[2:6, :3]

Pregnancies  Glucose  BloodPressure
2            8      100             64
3            1       89             66
4            0      137             40
5            5      116             74

In [ ]:
# Filter the dataset=========Pending
diabetes = data.loc[data["Outcome"] == 1, ['Pregnancies', 'Glucose']]
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      100             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
data.isnull()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin    BMI  \
0          False    False          False          False    False  False   
1          False    False          False          False    False  False   
2          False    False          False          False    False  False   
3          False    False          False          False    False  False   
4          False    False          False          False    False  False   
..           ...      ...            ...            ...      ...    ...   
763        False    False          False          False    False  False   
764        False    False          False          False    False  False   
765        False    False          False          False    False  False   
766        False    False          False          False    False  False   
767        False    False          False          False    False  False   

     DiabetesPedigreeFunction    Age  Outcome  
0                       False  False    False  
1                       False  False    False  
2                       False  False    False  
3                       False  False    False  
4                       False  False    False  
..                        ...    ...      ...  
763                     False  False    False  
764                     False  False    False  
765                     False  False    False  
766                     False  False    False  
767                     False  False    False  

[768 rows x 9 columns]

In [ ]:
#Data Preprocessing
#missing values represented by Nan
data.isnull().sum()


Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [ ]:
#Duplicate values
data.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...  
763    False
764    False
765    False
766    False
767    False
Length: 768, dtype: bool

In [ ]:
data.duplicated().sum()

np.int64(0)

In [ ]:
data['Age'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...  
763    False
764    False
765    False
766    False
767    False
Name: Age, Length: 768, dtype: bool

In [ ]:
data['BloodPressure'].isnull().sum()

np.int64(0)

In [ ]:
import numpy as np
data["Insulin"].replace(0, np.nan, inplace=True)
data.head()

/tmp/ipython-input-2087224012.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Insulin"].replace(0, np.nan, inplace=True)


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35      NaN  33.6   
1            1       85             66             29      NaN  26.6   
2            8      100             64              0      NaN  23.3   
3            1       89             66             23     94.0  28.1   
4            0      137             40             35    168.0  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
data.columns
#data.head()

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [ ]:
#columns_to_clean = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness',
                   # 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age']

for col in ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness',
                    'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome']:
    data[col].replace(0, np.nan, inplace=True)

/tmp/ipython-input-3078538701.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[col].replace(0, np.nan, inplace=True)


In [ ]:
data.head(20)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0           6.0    148.0           72.0           35.0      NaN  33.6   
1           1.0     85.0           66.0           29.0      NaN  26.6   
2           8.0    100.0           64.0            NaN      NaN  23.3   
3           1.0     89.0           66.0           23.0     94.0  28.1   
4           NaN    137.0           40.0           35.0    168.0  43.1   
5           5.0    116.0           74.0            NaN      NaN  25.6   
6           3.0     78.0           50.0           32.0     88.0  31.0   
7          10.0    115.0            NaN            NaN      NaN  35.3   
8           2.0    197.0           70.0           45.0    543.0  30.5   
9           8.0    125.0           96.0            NaN      NaN   NaN   
10          4.0    110.0           92.0            NaN      NaN  37.6   
11         10.0    168.0           74.0            NaN      NaN  38.0   
12         10.0    139.0           80.0            NaN      NaN  27.1   
13          1.0    189.0           60.0           23.0    846.0  30.1   
14          5.0    166.0           72.0           19.0    175.0  25.8   
15          7.0    100.0            NaN            NaN      NaN  30.0   
16          NaN    118.0           84.0           47.0    230.0  45.8   
17          7.0    107.0           74.0            NaN      NaN  29.6   
18          1.0    103.0           30.0           38.0     83.0  43.3   
19          1.0    115.0           70.0           30.0     96.0  34.6   

    DiabetesPedigreeFunction  Age  Outcome  
0                      0.627   50      1.0  
1                      0.351   31      NaN  
2                      0.672   32      1.0  
3                      0.167   21      NaN  
4                      2.288   33      1.0  
5                      0.201   30      NaN  
6                      0.248   26      1.0  
7                      0.134   29      NaN  
8                      0.158   53      1.0  
9                      0.232   54      1.0  
10                     0.191   30      NaN  
11                     0.537   34      1.0  
12                     1.441   57      NaN  
13                     0.398   59      1.0  
14                     0.587   51      1.0  
15                     0.484   32      1.0  
16                     0.551   31      1.0  
17                     0.254   31      1.0  
18                     0.183   33      NaN  
19                     0.529   32      1.0

In [ ]:
data.isnull().sum()

Pregnancies                 111
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                     500
dtype: int64

In [ ]:
# Handling the missing values
for col in ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness',
                    'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome']:
            data[col].fillna(data[col].mean(), inplace=True)

/tmp/ipython-input-380390772.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[col].fillna(data[col].mean(), inplace=True)


In [ ]:
data.head(20)

Pregnancies  Glucose  BloodPressure  SkinThickness     Insulin        BMI  \
0      6.000000    148.0      72.000000       35.00000  155.548223  33.600000   
1      1.000000     85.0      66.000000       29.00000  155.548223  26.600000   
2      8.000000    100.0      64.000000       29.15342  155.548223  23.300000   
3      1.000000     89.0      66.000000       23.00000   94.000000  28.100000   
4      4.494673    137.0      40.000000       35.00000  168.000000  43.100000   
5      5.000000    116.0      74.000000       29.15342  155.548223  25.600000   
6      3.000000     78.0      50.000000       32.00000   88.000000  31.000000   
7     10.000000    115.0      72.405184       29.15342  155.548223  35.300000   
8      2.000000    197.0      70.000000       45.00000  543.000000  30.500000   
9      8.000000    125.0      96.000000       29.15342  155.548223  32.457464   
10     4.000000    110.0      92.000000       29.15342  155.548223  37.600000   
11    10.000000    168.0      74.000000       29.15342  155.548223  38.000000   
12    10.000000    139.0      80.000000       29.15342  155.548223  27.100000   
13     1.000000    189.0      60.000000       23.00000  846.000000  30.100000   
14     5.000000    166.0      72.000000       19.00000  175.000000  25.800000   
15     7.000000    100.0      72.405184       29.15342  155.548223  30.000000   
16     4.494673    118.0      84.000000       47.00000  230.000000  45.800000   
17     7.000000    107.0      74.000000       29.15342  155.548223  29.600000   
18     1.000000    103.0      30.000000       38.00000   83.000000  43.300000   
19     1.000000    115.0      70.000000       30.00000   96.000000  34.600000   

    DiabetesPedigreeFunction  Age  Outcome  
0                      0.627   50      1.0  
1                      0.351   31      NaN  
2                      0.672   32      1.0  
3                      0.167   21      NaN  
4                      2.288   33      1.0  
5                      0.201   30      NaN  
6                      0.248   26      1.0  
7                      0.134   29      NaN  
8                      0.158   53      1.0  
9                      0.232   54      1.0  
10                     0.191   30      NaN  
11                     0.537   34      1.0  
12                     1.441   57      NaN  
13                     0.398   59      1.0  
14                     0.587   51      1.0  
15                     0.484   32      1.0  
16                     0.551   31      1.0  
17                     0.254   31      1.0  
18                     0.183   33      NaN  
19                     0.529   32      1.0

In [ ]:
def age_group(age):
  if age<=25:
    return "Youth"
  elif age>25 and age < 50:
    return "Middle"
  else:
    return "Old"
data["Age_group"] = data["Age"].apply(age_group)
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness     Insulin   BMI  \
0     6.000000    148.0           72.0       35.00000  155.548223  33.6   
1     1.000000     85.0           66.0       29.00000  155.548223  26.6   
2     8.000000    100.0           64.0       29.15342  155.548223  23.3   
3     1.000000     89.0           66.0       23.00000   94.000000  28.1   
4     4.494673    137.0           40.0       35.00000  168.000000  43.1   

   DiabetesPedigreeFunction  Age  Outcome Age_group  
0                     0.627   50      1.0       Old  
1                     0.351   31      1.0    Middle  
2                     0.672   32      1.0    Middle  
3                     0.167   21      1.0     Youth  
4                     2.288   33      1.0    Middle

In [ ]:
# Drop column
data.drop(['Age_group'], axis=1, inplace=True)
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness     Insulin   BMI  \
0     6.000000    148.0           72.0       35.00000  155.548223  33.6   
1     1.000000     85.0           66.0       29.00000  155.548223  26.6   
2     8.000000    100.0           64.0       29.15342  155.548223  23.3   
3     1.000000     89.0           66.0       23.00000   94.000000  28.1   
4     4.494673    137.0           40.0       35.00000  168.000000  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50      1.0  
1                     0.351   31      1.0  
2                     0.672   32      1.0  
3                     0.167   21      1.0  
4                     2.288   33      1.0

In [ ]:
#Drop rows
data.drop([0,1], axis=0, inplace=True)
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness     Insulin   BMI  \
2     8.000000    100.0           64.0       29.15342  155.548223  23.3   
3     1.000000     89.0           66.0       23.00000   94.000000  28.1   
4     4.494673    137.0           40.0       35.00000  168.000000  43.1   
5     5.000000    116.0           74.0       29.15342  155.548223  25.6   
6     3.000000     78.0           50.0       32.00000   88.000000  31.0   

   DiabetesPedigreeFunction  Age  Outcome  
2                     0.672   32      1.0  
3                     0.167   21      1.0  
4                     2.288   33      1.0  
5                     0.201   30      1.0  
6                     0.248   26      1.0

In [ ]:
# Working with more than one dataFrame without mentioning the index
df1=pd.DataFrame({
    "A":[10,20,30],
    "B":[40,50,60]
})
df2=pd.DataFrame({
    "C":[10,20,30],
    "D":[40,50,60]
})
print(df1)

    A   B
0  10  40
1  20  50
2  30  60


In [ ]:
# Working with more than one dataFrame with mentioning the index
df1=pd.DataFrame({
    "A":[10,20,30],
    "B":[70,50,60]

}, index=["a", "y", "x"])
df2=pd.DataFrame({
    "C":[100,200,300],
    "D":[400,500,600]

},index=["a", "b", "c"])
print(df1)
print("====================================")
print(df2)

    A   B
a  10  70
y  20  50
x  30  60
     C    D
a  100  400
b  200  500
c  300  600


# Combining data frame
1) Join= based on index [inner, outer, left, right]
2) Merge= based on common columns
3) concat=

In [ ]:
#Join=left join
df = df1.join(df2, how="left")
df

A   B      C      D
a  10  70  100.0  400.0
y  20  50    NaN    NaN
x  30  60    NaN    NaN

In [ ]:
# right join
df=df1.join(df2, how="right")
df

A     B    C    D
a  10.0  70.0  100  400
b   NaN   NaN  200  500
c   NaN   NaN  300  600

In [ ]:
#inner join
df=df1.join(df2, how="inner")
df

A   B    C    D
a  10  70  100  400

In [ ]:
#outer join
df = df1.join(df2, how="outer")
df

A     B      C      D
a  10.0  70.0  100.0  400.0
b   NaN   NaN  200.0  500.0
c   NaN   NaN  300.0  600.0
x  30.0  60.0    NaN    NaN
y  20.0  50.0    NaN    NaN

In [ ]:
#Merge
dataf1=pd.DataFrame({
    "A":[1,2,3],
    "B":[4,5,6]

}, index=["z", "x", "y"])
dataf2=pd.DataFrame({
    "A":[100,200,300],
    "D":[400,500,600]

},index=["a", "b", "c"])

print(dataf1)
print(dataf2)

   A  B
z  1  4
x  2  5
y  3  6
     A    D
a  100  400
b  200  500
c  300  600


In [ ]:
df = dataf1.merge(dataf2, on="A", how="left")
df

A  B   D
0  1  4 NaN
1  2  5 NaN
2  3  6 NaN

In [ ]:
df = dataf1.merge(dataf2, on="A", how="right")
df

A   B    D
0  100 NaN  400
1  200 NaN  500
2  300 NaN  600

In [ ]:
df = dataf1.merge(dataf2, on="A", how="inner")
df

Empty DataFrame
Columns: [A, B, D]
Index: []

In [ ]:
df=dataf1.merge(dataf2, on="A", how="outer")
df

A    B      D
0    1  4.0    NaN
1    2  5.0    NaN
2    3  6.0    NaN
3  100  NaN  400.0
4  200  NaN  500.0
5  300  NaN  600.0

In [ ]:
#Concate
dataframe1=pd.DataFrame({
    "A":[1,2,3],
    "B":[4,5,6]

}, index=["z", "x", "y"])
dataframe2=pd.DataFrame({
    "A":[100,200,300],
    "D":[400,500,600]

},index=["a", "b", "c"])
print(dataframe1)
print(dataframe2)

   A  B
z  1  4
x  2  5
y  3  6
     A    D
a  100  400
b  200  500
c  300  600


In [ ]:
df=pd.concat([dataframe1, dataframe2], axis=0)
df

A    B      D
z    1  4.0    NaN
x    2  5.0    NaN
y    3  6.0    NaN
a  100  NaN  400.0
b  200  NaN  500.0
c  300  NaN  600.0